### ISSUE TITLE
ktppath error

### ISSUE THREAD

**Issue by saranzeb** [YukaLangbuana/KTP-OCR#10]
when I am  running  from the command line it gives me these two errors  
 I have attached screen short 

"Traceback (most recent call last):
  File "ocr.py", line 47, in <module>
    ocr = KTPOCR(ktppath)
  File "D:\video monitoring\first four\KTP-OCR-master\ktpocr\extractor.py", line 13, in __init__
    self.gray = cv2.cvtColor(self.image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor' "

![Error](https://user-images.githubusercontent.com/79502021/148320742-fffd2dcb-d87f-44f4-9261-7c7a239c2f08.PNG)

"it seems I am not giving the proper path for image please can you point out where i am doing mistake where I am doing mistake

**Comment by power4d** [comment]
did the issue got solved? please enlighten me

**Comment by Adiguna7** [comment]
What if it's just like this:

`ktpocr/dataset/ktp1.png`

I'm not a daily user of Windows, But afaik `/<path>` with `<path>` are different.

If on linux, `/<path>` will be absolute path and `<path>` will be relative path.  

[reference](http://differencebetween.net/technology/difference-between-absolute-and-relative-path/#:~:text=In%20simple%20words%2C%20an%20absolute,directory%20you%20are%20working%20on)
