### ISSUE TITLE
Kenapa muncul error seperti ini saat dicoba?

### ISSUE THREAD

**Issue by anggimufid** [YukaLangbuana/KTP-OCR#14]
Ini kenapa yaa, muncul error kayak gini? 

Traceback (most recent call last):
  File "ocr.py", line 47, in <module>
    ocr = KTPOCR(ktppath)
  File "/var/www/html/KTP-OCR/ktpocr/extractor.py", line 16, in __init__
    self.master_process()
  File "/var/www/html/KTP-OCR/ktpocr/extractor.py", line 110, in master_process
    self.extract(raw_text)
  File "/var/www/html/KTP-OCR/ktpocr/extractor.py", line 106, in extract
    self.result.rw = word.split('/')[1].strip()
IndexError: list index out of range

**Comment by jalal-as6** [comment]
sama nih, muncul error spt ini solusinya gmn ya?

**Comment by homidinis** [comment]
bump, saya menemukan masalah yang sama

**Comment by strongpapazola** [comment]
itu gara2 ada error ketika parsing RT RW

**Comment by strongpapazola** [comment]
solusinya cari file extractor.py trus tambahin ini
![image](https://github.com/user-attachments/assets/32f0949e-7a78-4ae6-a90f-66247c45f7a1)

**Comment by strongpapazola** [comment]
<pre>def extract(self, extracted_result):
        # print(extracted_result.replace('\n', ' -- '))
        print(extracted_result) # TAMBAHIN INI
        exit() # TAMBAHIN INI</pre>
